# pre-commit hooks to ensure our agreed coding conventions
# see https://pre-commit.com for more information
repos:
  # See https://pre-commit.com/hooks.html for more hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-aws-credentials
      - id: check-added-large-files

  # See https://github.com/antonbabenko/pre-commit-terraform
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.29.0
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terraform_validate
      # - id: terraform_docs
      - id: terraform_tflint
        args:
          - "args=--enable-rule=terraform_documented_variables"
          - "args=--enable-rule=terraform_dash_in_resource_name"
          - "args=--enable-rule=terraform_documented_outputs"
          - "args=--enable-rule=terraform_documented_variable"
          - "args=--enable-rule=terraform_module_pinned_source"
          - "args=--enable-rule=terraform_module_semver_source"
