name: terraform

on:
  pull_request:
  push:
    branches: [master]
env:
  tf_version: "latest"
  tf_working_dir: "."
jobs:
  # terraform:
  #   name: "Terraform"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@master
  #     - name: "Terraform Init"
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.tf_version }}
  #         tf_actions_subcommand: "init"
  #         tf_actions_working_dir: ${{ env.tf_working_dir }}
  #         tf_actions_comment: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        run: |
          curl -LO https://raw.github.com/robertpeteuil/terraform-installer/master/terraform-install.sh
          chmod +x terraform-install.sh
          ./terraform-install.sh -a
      - name: Terraform init
        run: |
          terraform init
  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
